### ISSUE TITLE
node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly

### ISSUE THREAD

**Issue by wawanopoulos** [imagemin/pngquant-bin#78]
I'am getting this error today when i try to make a npm update on my project:

> pngquant-bin@4.0.0 postinstall /var/www/palm/20180315202846/node_modules/pngquant-bin
> > node lib/install.js
> 
>   ⚠ The `/var/www/pp/20180315202846/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
>   ⚠ pngquant pre-build test failed
>   ℹ compiling from source
>   ✔ pngquant pre-build test passed successfully
>   ✖ RequestError: pngquant failed to build, make sure that libpng-dev is installed
>     at ClientRequest.req.once.err (/var/www/pp/20180315202846/node_modules/pngquant-bin/node_modules/got/index.js:111:21)
>     at Object.onceWrapper (events.js:272:13)
>     at ClientRequest.emit (events.js:180:13)
>     at ClientRequest.onConnect (/var/www/pp/20180315202846/node_modules/pngquant-bin/node_modules/tunnel-agent/index.js:168:23)
>     at Object.onceWrapper (events.js:272:13)
>     at ClientRequest.emit (events.js:180:13)
>     at Socket.socketOnData (_http_client.js:476:11)
>     at Socket.emit (events.js:180:13)
>     at addChunk (_stream_readable.js:269:12)
>     at readableAddChunk (_stream_readable.js:256:11)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ^C
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-03-15T20_19_09_479Z-debug.log

I already install libpng-dev library, and i always get this error.

**Comment by fifthsage** [comment]
I have same case.

it suddenly comes up last night.

**Comment by mybigman** [comment]
same issue :(

**Comment by thecodejack** [comment]
anyone got any resolution for this?

**Comment by anthonyaam** [comment]
I have the same problem beginning yesterday.

**Comment by danherd** [comment]
Has anyone got a temporary fix for this?

**Comment by anthonyaam** [comment]
@danherd use pngquant-bin 3.1.1 for now.

**Comment by danherd** [comment]
@anthonyaam alas, this package is a dependency of a dependency of a dependency... and the version being used is not something I can control!

**Comment by anthonyaam** [comment]
@danherd if you have someone on your project that hasn't run npm update yet you could have them check in a package-lock.json file that references pngquant-bin 3.1.1.

If that's not an option then your situation becomes more difficult...I think you'll have to submit PRs to update the dependencies you're importing or just wait for this root issue to be resolved...

**Comment by danherd** [comment]
@anthonyaam yeah I think I can probably wait it out - funnily enough, even with this error being displayed on `yarn install --production`, all my assets seem to build OK anyway!

**Comment by wawanopoulos** [comment]
Could you please provide a quick fix for this issue ? It's very boring..

**Comment by skatetdieu** [comment]
The issue seems to be this commit added a few days ago. It stops npm if the build fails:
https://github.com/imagemin/pngquant-bin/commit/a518db6f9283ca0dd435fca8436e4e9232d49b82

And yes, I am also having this issue.

**Comment by wawanopoulos** [comment]
@skatedieu did you find any workaround? Or we need to waot a fix?

**Comment by skatetdieu** [comment]
I don't have a workaround, unfortunately. 

We have to either just wait or submit a pull request removing this line of code.

**Comment by sroy19** [comment]
I had the same issue but it is resolved by first installing libpng-dev
Need to follow the following steps:
sudo apt-get install libpng-dev
and then run
npm install -g pngquant-bin

that fixes the issue for me.

@anthonyaam no need to go to old versions for pngquant-bin

**Comment by skatetdieu** [comment]
@sroy19 I ran that in my server and got a message that no package libpng-dev is available. :/

**Comment by wawanopoulos** [comment]
@sroy19 This fix doesn't work for me. I always get this error when deploying my app..

**Comment by drzippie** [comment]
To build pngquant binary you need to have installed make.
apt-get install make
(or similar)
Found viewing install.js
[...]

binBuild.url('http://pngquant.org/pngquant-2.10.1-src.tar.gz', [
			'rm ./INSTALL',
			`./configure --prefix="${bin.dest()}"`,
			`make install BINPREFIX="${bin.dest()}"`
[..]

**Comment by wawanopoulos** [comment]
@sro19 which version of libpng-dev did you install?

**Comment by velu76** [comment]
I got similiar error for Laravel in Ubuntu 17.10.  I used @sory19 method as below:
-------
> I had the same issue but it is resolved by first installing libpng-dev
> Need to follow the following steps:
> sudo apt-get install libpng-dev
> and then run
> npm install -g pngquant-bin

Still had same error.  This is what I did.
 1. Removed the "node_modules" folder: `sudo rm -rf node_modules`
 2. Re-ran `npm install`

And it worked after that.

**Comment by wawanopoulos** [comment]
@velu76 Which version of libpng-dev did you install ?

**Comment by skatetdieu** [comment]
I am on CentOS and there is no libpng-dev package to install with yum. I have installed libpng. But this package wants libpng-dev and will not install without it. 

Why would it seem like a good idea to stop people from being able to deploy just because a package 5 dependencies down isn't fully working?

**Comment by skatetdieu** [comment]
I made a pull request commenting that line out and adding notes for the npm install exit to be more discretionary to only environments for systems that can have libpgn-dev and just let other systems continue installing npm packages. 

https://github.com/imagemin/pngquant-bin/pull/79

Hopefully we get an answer soon.

**Comment by velu76** [comment]
@wawanopoulos,

I tried installing pngquant-bin 3.1.1 but it too ended up in the error. Therefore, as mentioned earlier, I removed the node_modules folder and reinstalled everything from scratch.

**Comment by fifthsage** [comment]
@velu76 Could you let me know which version do you use ?

i tried on ubuntu 17.10, it works. (both 3.1.1 and 4.0.0) but debian stretch, it doesn't work.

**Comment by velu76** [comment]
@fifthsage I am using Ubuntu 17.10

**Comment by iamnibin** [comment]
Is there any way to resolve the issue in centos?
We cannot change the package version because it is dependency of dependency of  dependency. 
one more observation which we noticed it is checking for **libpng-dev** in centos the package name is **libpng-devel** it is saying the lib is not found.

**Comment by fifthsage** [comment]
i tested debian jessie, sid, wheezy, stretch.

Success: jessie, sid
Failed: wheezy, stretch

**Comment by wawanopoulos** [comment]
I am on stretch and it doesn't work

**Comment by jimnybob** [comment]
I don't understand npm and npm doesn't understand versioning. For anyone else struggling, my "fix" was to remove our '**image-webpack-loader**' package dependency (which ultimately removed transitive dependency to imagemin-pngquant and pngquant-bin).

**Comment by RomanIsko** [comment]
Same issue when building project with `maven:3.5` docker image using Jenkinsfile
```
pipeline {
  agent any
  stages {
    stage('compile') {
      agent {
        docker {
          image 'maven:3.5'
          args '-v /var/lib/jenkins/.m2:/root/.m2 --user root'
        }
      }
      steps {
        sh 'apt update && apt install -y libpng-dev'
        sh 'mvn -B -DskipTests -e clean package'
      }
    }
  }
}
```

```
[INFO] > pngquant-bin@4.0.0 postinstall /var/lib/jenkins/jobs/[EDITED]]/workspace@2/ui/node_modules/pngquant-bin
[INFO] > node lib/install.js
[INFO] 
[ERROR]   ⚠ The `/var/lib/jenkins/jobs/[EDITED]/workspace@2/ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
[ERROR]   ⚠ pngquant pre-build test failed
[ERROR]   ℹ compiling from source
[ERROR]   ✔ pngquant pre-build test passed successfully
[ERROR]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
[ERROR]     at Promise.all.then.arr (/var/lib/jenkins/jobs/[EDITED]/workspace@2/ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
[ERROR]     at process._tickCallback (internal/process/next_tick.js:103:7)
..............................
..............................
[WARNING] npm WARN material-ui-number-input@5.0.24 requires a peer of material-ui@^0.18.6 but none was installed.
[ERROR] npm ERR! Linux 4.4.0-116-generic
[ERROR] npm ERR! argv "/var/lib/jenkins/jobs/[EDITED]/workspace@2/ui/target/node/node" "/var/lib/jenkins/jobs/[EDITED]/workspace@2/ui/target/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v6.9.1
[ERROR] npm ERR! npm  v3.10.8
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script 'node lib/install.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node lib/install.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs pngquant-bin
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls pngquant-bin
[ERROR] npm ERR! There is likely additional logging output above.
```

Without Docker agent it works without any errors
```
pipeline {
  agent any
  tools {
    maven 'maven3.5'
  }
  stages {
    stage ('Build') {
      steps {
        sh 'mvn -B -DskipTests -e clean package'
      }
    }
  }
}
```

**Comment by bodny** [comment]
Installing `make`, `gcc` and `libpng-dev` fixed issue for me.

I'm using npm in docker container. My docker container environment:
```
# cat /etc/issue
Debian GNU/Linux 9 \n \l
# cat /etc/debian_version
9.4
# node -v
v8.10.0
# npm -v
5.7.1
```

To install above mentioned packages on Debian/Ubuntu you can run:
```
apt-get install --no-install-recommends gcc make libpng-dev
```

**Comment by flavio-jr** [comment]
Even with the version 3.1.1 in my package-lock.json, the dependecy tries to use the version 4.0.0

**Comment by gFelicio** [comment]
As @velu76 and @sory19 said, I followed their method:

´sudo apt-get install libpng-dev´
´npm install -g pngquant-bin´

Since I had already 'npm install' in my repo/project folder, I then ran
´sudo rm -rf node_modules´

then, still in my repository/project folder
´npm install --no-bin-links´

And it works right now.

I don't know if it's just a temporary fix, actually, but I can work for now.

**Comment by skatetdieu** [comment]
I finally got it to work on my server by installing `libpng-devel`. I am on CentOS.

**Comment by fifthsage** [comment]
@bodny thanks it works for me.

**Comment by santoshyadav198613** [comment]
Any update on how to make it work on windows. I am using image-webpack-loader which has dependency on this package, was working fine till last friday.

**Comment by Duske** [comment]
On my Ubuntu 17.10 system the problem was with libpng as well. pngquant-bin delivers its own executable in `vendor`. When this version works, you won't get into the phase where it tries to compile from source which is troublesome for some of us.
 
In my case the version from `vendor` did not work, because ` libpng12.so.0` was missing.
As soon as I installed it by following [this comment](https://github.com/tcoopman/image-webpack-loader/issues/95#issuecomment-309557855), the version from `vendor` worked :)

**Comment by nicolas-lutic** [comment]
The @bodny solution works for debian in docker environnement.
Thanks, you save my day.

**Comment by tongv** [comment]
I'm suffering from this problem. It seems to be a new problem.

**Comment by tongv** [comment]
@bodny  tks, it works for me!

**Comment by kslr** [comment]
I am using Arch, the platform does not have dev package.
Can you fix it quickly?

**Comment by svallamsetti** [comment]
@skatetdieu I installed `libpng-devel` on the server but still facing the same issue. Do I require a specific version of `libpng-devel` to be installed? My server is on CentOS and contains node v6.11.0 and npm v3.10.10.

**Comment by mikemand** [comment]
Also on CentOS here. `libpng-devel-1.5.13-7.el7_2.x86_64` is installed, but it keeps looking for `libpng-dev`.

```
error node_modules/imagemin-pngquant/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: node_modules/imagemin-pngquant/node_modules/pngquant-bin
Output:
⚠ The `node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
```

**Comment by serginator** [comment]
In `CentOS` I've also tried to compile version 1.6.34 of libpng and latest pngquant from kornelski's github, but `imagemin-pngquant` still tries to use it's own binary, not the system's one, and keeps failing.

**Comment by SanderSander** [comment]
Got the same error in my docker container on the `node:9-alpine` image.
`libpng-dev` is allready installed. 

```
[4/6] ⠈ optipng-bin:   ℹ compiling from source
error An unexpected error occurred: "/root/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: sh
Arguments: -c node lib/install.js
Directory: /root/node_modules/pngquant-bin
Output:
⚠ spawn /root/node_modules/pngquant-bin/vendor/pngquant ENOENT
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/root/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
```

**Comment by SanderSander** [comment]
The error message is incorrect!!! 

First you need `openssl` furthermore the build requires bash to be installed. 

```
wget http://pngquant.org/pngquant-2.10.1-src.tar.gz
Connecting to pngquant.org (83.169.2.68:80)
Connecting to pngquant.org (83.169.2.68:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```
```
~/pngquant-2.10.1 # ./configure --prefix=/root/test/
env: can't execute 'bash': No such file or directory
```

So after running `apk add openssl bash` it works fine on alpine.

**Comment by skatetdieu** [comment]
At first when I installed `libpgn-devel` on CentOS it didn't work. But then after a few more tries it just worked. I don't know why that is. It's weird. 

I am using Node 6 and NPM 3.

**Comment by kslr** [comment]
I currently solve this problem through yarn

**Comment by dapseen** [comment]
Hi on ubuntu 17.01 

`apt-get install --no-install-recommends gcc make libpng-dev`

it works for me @bodny

**Comment by s17billsp** [comment]
## Potential quick fix if you are on CentOS 7
On _CentOS 6_, latest libpng-devel version is **1.2.49** which is what I think is causing these issues.
On _CentOS 7_, latest is **1.5.13** which appears to be working, so updating this package might fix this.

## Workaround
I managed to fix this on CentOS 6, by updating my project's package.json
to use `"imagemin-pngquant": "5.0.0"` and running npm install again. (was "^5.0.0" before)

### Possible cause
imagemin-pngquant 5.0.0 uses pngquant-bin 3.1.1 which does compile successfully, while 5.1.0 uses pngquant-bin 4.0.0 and is causing compilation issues with libpng-devel.

**Comment by mikemand** [comment]
@s17billsp: My CentOS server has libpng-devel v1.5.13 already and things are not working. I will attempt to fix the version of `imagemin-pngquant` to `5.0.0` and see what happens.

**Comment by jhill-dci** [comment]
@skatetdieu yum installing `libpng-devel` fixed this for me on RHEL 7.  THANK YOU!

**Comment by mikemand** [comment]
Setting `imagemin-pngquant` to `5.0.0` did not work. I've run out of time, knowledge, and patience to fix this issue.

I'm compiling assets locally and then committing them in git, instead. This is ridiculous.

**Comment by svallamsetti** [comment]
I managed to fix this[temporarily] on CentOS 6 using `npm shrinkwrap` command. 
This helps us to manage the inter-dependencies.

1. Set the `imagemin-pngquant` to version "5.0.0" i.e `"imagemin-pngquant": "5.0.0"`
2. Remove the  `"pngquant-bin": "3.1.1"`  dependency from `imagemin-pngquant`  requires and add `"dependencies": {
                "pngquant-bin": {
                    "version":"3.1.1"
                }
            }`
3. Similarly, remove the `"imagemin-pngquant": "5.0.1"` dependency from `"img-loader"` requires  and add "dependencies":{
                "imagemin-pngquant": {
                    "version":"5.0.0"
                }
            }
4. run `npm shrinkwrap`

Note: this command is useful only once and for the second time it replaces the `npm-shrinkwrap.json` file with latest available dependencies. Moreover, I used this to avoid the issue facing only on CI server. So I only ran `npm shrinkwrap` when I want a build to happen.

**Comment by softwaredeveloperca** [comment]
For Ubuntu I used:
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb

**Comment by mashhur** [comment]
same problem here with macOS..
anybody has a workaround?
ERROR: RequestError: pngquant failed to build, make sure that libpng is installed.
(comes from laravel-mix install)

**Comment by ngoctp** [comment]
The issue comes from new release of `imagemin-pngquant` v5.1 requires pngquant-bin@4.0.0
The quick fix is to downgrade `imagemin-pngquant` to 5.0.* which is using pngquant-bin@3.1.1

Run this command and commit your package.json
`npm install --save-exact imagemin-pngquant@5.0.*`

**Comment by Advaith3600** [comment]
I managed to fix this problem by installing `libpng-dev` in Ubuntu 17.10.
Just run `sudo apt install libpng-dev` and then `npm update`

**Comment by burhan-kun** [comment]
same problem on centos i tried all... yum install libpng-devel.. installed then run npm again, error.

**Comment by mythrnr** [comment]
I think it will not be a fundamental solution and not be applied to all, but I was able to install it with the `--force` option (using Docker's node: 9.3.0-alpine image)

**Comment by victorvoronin** [comment]
> same problem on centos i tried all... yum install libpng-devel.. installed then run npm again, error.

I have installed all packages with libpng in title on Centos. It works for me
`# yum install libpng* -y`

**Comment by rangermeier** [comment]
same problem here on Fedora 27, managed to get it to work by installing libpng12 and libpng12-devel
`# dnf install libpng12 libpng12-devel`

**Comment by Reduced-Stickers** [comment]
@rangermeier your suggestion worked wonderfully! Thank you!

**Comment by magemaniac33** [comment]
@rangermeier Works perfect, thank you!

**Comment by cristim** [comment]
I'm still struggling to get this work on CentOS6, the recommended `yum install libpng* -y` doesn't just work.
- building native packages against relatively recent node.js versions requires a compiler that supports C++11 and for that we were using devtoolset-3 for a while now because the default CeotOS6 compiler is too old.
- I noticed that `npm install` fails when using the devtoolset toolchain but would manage to install 
pngquant-bin when not using the devtoolset environment.

As a workaround I'm now trying to perform the `npm install` in two steps: once inside the devtoolset in order to install most modules, then exit the devtoolset and run it again just for pngquant-bin. I'll report back once I have some results.

**Comment by skatetdieu** [comment]
@cristim I used it on CentOS but had to install `libpgn-devel` with yum instead of libpng.

**Comment by cristim** [comment]
@skatetdieu I have installed all the libpng packages, including libpng-devel. As I said, the problem in my case seems to be caused by the devtoolset. It works without it for pngquant-bin, but I need it for other native packages that I require a C++11 compiler.

**Comment by skatetdieu** [comment]
@cristim hmm, yeah I don't know how to resolve that. I just installed `libpng-devel` and it worked for me.

**Comment by mybigman** [comment]
Still not working on Debian 9.4 :(

Any ideas when it will be resolved?

**Comment by Mmzer** [comment]
same problem to me! I fixed it use this:
1. mofidy package.json
```
...
    "image-webpack-loader": "^4.2.0",
    "imagemin-pngquant":"5.0.0",
    "pngquant-bin":"3.1.1",
...
```
2. run this bash:
```
yum install -y gcc gcc-c++ make openssl-devel libpng libpng-devel
```
I don't know why so solved！

**Comment by hubo1016** [comment]
It seems that the pre-compiled binary is linking to libpng12, so you must install libpng12 to allow the pre-compiled to work

on CentOS 7:

```
yum install -y libpng12
```

Or install the libpng-devel to build it

```
yum install -y libpng-devel
```
as well as other dependencies (gcc, make, ...)

**Comment by hubo1016** [comment]
It's funny that this binary has been uploaded for three years, and was broken at least for 5 months (#73) because new OS are shipping libpng15 instead of libpng12, but still not noticed until v4.0.0...

**Comment by cristim** [comment]
If we do ship binaries, can't we ship a static binary instead of linking and then depending on whatever is available on the host?

**Comment by hasusuf** [comment]
I was able to solve this issue on my `node:9-alpine` container by installing the following `apk add --no-cache make gcc g++ libc-dev libpng-dev bash`
or `apk add --no-cache bash alpine-sdk libpng-dev` if you don't care about the images' size.

**Comment by yyynnn** [comment]
some help for windows users will be appreciated

**Comment by bokideckonja** [comment]
I ran:
sudo apt-get install libpng-dev
before npm install and it solved it for me.

Hope it helps.

**Comment by bwml** [comment]
On Centos 7 | NPM 3.10.10 | Node v6.14.0
This worked for me:
sudo yum install libpng-devel

**Comment by chasebolt** [comment]
i am also hitting this same issue. it appears during install this package does a call over to http://pngquant.org and denying the connection. testing with telnet pngquant.org tells me to visit http://sblam.com

the connection denied to their main site is currently failing the install.

```
1525392226.494      0 172.22.6.8 TCP_DENIED/200 0 CONNECT pngquant.org:80 - HIER_NONE/- -
```

**Comment by 3kynox** [comment]
I'm on debian 9.4, none of the above workarounds works.

Repo owner, please merge available PR's and correct this please.

Laravel-mix / Spark installations completely unavailable because of this!

**Comment by rico-ocepek** [comment]
Same here on Alpine3.7, yarn install wont work - one of the most annoying issues out there right now I am expiriencing it with every new installation on every new OS and still don't have a final fix..

**Comment by robindirksen1** [comment]
For Laravel/Spark users, see this comment (CentOS): https://github.com/JeffreyWay/laravel-mix/issues/1611#issuecomment-387254894 - this fixed it for me.

**Comment by ragonzalezm19** [comment]
This work for me, Ubuntu 18.04 https://stackoverflow.com/a/49465604

**Comment by tyler36** [comment]
Same issue for me on Win10

**Comment by pkbhuiyan** [comment]
In my case:
1.npm update gulp
2.npm install

and that solve in my case... :P

**Comment by misterspelik** [comment]
Hi guys also take a note that this issue can be related to non-existing swap partition at your VMs.
I just created it it started to work.
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by dejwoo** [comment]
If anyone is struggling in _Debian 9(Stretch)_ or Debian based Docker container,

`apt-get -y install libpng* nodejs make gcc g++ libc-dev bash`

has solved the issue for me. After that `npm install` successfully installed pnguant-bin

**Comment by InstanceOfMichael** [comment]
> This work for me, Ubuntu 18.04 https://stackoverflow.com/a/49465604

```
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb
```

**Comment by james-nesbitt** [comment]
@InstanceOfMichael is there any reason that you used http instead of https?

**Comment by moff** [comment]
Had the same issue on Ubuntu 18.04, fixed with `sudo apt install libpng-dev`

**Comment by SimonJ** [comment]
@moff Thanks worked for me too :)

**Comment by skeith69** [comment]
run sudo apt install libpng-dev.
delete node_modules folder and package-lock.json file.
run npm install.
you're welcome.

**Comment by ravanscafi** [comment]
This worked for me, using `node:alpine` (by this time, `10.5.0`)

```dockerfile
FROM node:alpine

RUN apk add --no-cache --update make gcc g++ libc-dev libpng-dev automake autoconf libtool
```

**Comment by Bwilliamson55** [comment]
@InstanceOfMichael  and @ragonzalezm19 
Installing the older version worked on Ubuntu 18.04 LTS server- for laravel 5.6.

**Comment by siddharthlatest** [comment]
Any updates on this? Has there been a new release which fixes this?

As some others have pointed, my use of pngquant isn't direct and I'm unable to make any changes. If you push a patch release fixing this, it should start working for everyone who's using this indirectly.

**Comment by Tohsig** [comment]
Ran into this on CentOS 7.5 using yarn. Stumbled across issue #77 and realized I needed `libpng12` and `libpng12-devel`. Install is working now.

**Comment by anaxamaxan** [comment]
Solution listed by @skeith69 worked for me using Ubuntu 18.04 LTS on Windows WSL with a fresh Laravel 5.6 install.

**Comment by benallfree** [comment]
Centos 6.10

```bash
sudo yum install -y gcc make libpng-devel
yarn
```

**Comment by brickgale** [comment]
getting an error on running `npm install -g pngquant-bin`. running this command instead `npm install -g pngquant-bin --allow-root  --unsafe-perm=true`. got this from issue #81

**Comment by Begi** [comment]
For those building in docker env with alpine image:

```
RUN apk add --no-cache \
    # Prerequisites for pngquant-bin
    build-base \
    libpng-dev \
    lcms2-dev \
    bash
```
You can check the dependencies in the build log of pngquant https://pkgs.alpinelinux.org/package/edge/community/ppc64le/pngquant

```
>>> pngquant: Installing for build: build-base libpng-dev lcms2-dev bash
```

**Comment by projects-logiciel** [comment]
Hii guys here same problem face but I solved problem I thik that is help able for you so try this.

should install these both package
    sudo apt-get install libpng-dev
    npm install -g pngquant-bin

1. first find your project directory.
2. should your project directory also permitted.

in exp project root directory is projects
Exp: /var/www/html/projects
sudo chmod -R 777 projects

4. cd /var/www/html/projects/your_project
5. npm install
6. npm run dev.

try this way I hope you get better result.

**Comment by irshad-logiciel** [comment]
Hii guys here same problem face but I solved problem I thik that is help able for you so try this.

should install these both package
    sudo apt-get install libpng-dev
    npm install -g pngquant-bin

1. first find your project directory.
2. should your project directory also permitted.

in exp project root directory is projects
Exp: /var/www/html/projects
sudo chmod -R 777 projects

4. cd /var/www/html/projects/your_project
5. npm install
6. npm run dev.

try this way I hope you get better result.

**Comment by callmeaponte** [comment]
+1 for this. Any solutions aka love for those of us stuck w/ Windows machines at work would be much appreciated :)

**Comment by vhsmoke** [comment]
Working solution for Windows very needs!

**Comment by taghouti** [comment]
fixed, thnx sroy19

**Comment by TheFox** [comment]
> it suddenly comes up last night.

> It's very boring

This is so npm typically. Everything is unstable like shit. You install random shit, you get random errors, you get random answers from the community, and nothing is working.

Using npm is so frustrating. I still wonder why even using npm at all.

**Comment by aredridel** [comment]
CentOS 7.5: I had forgotten gcc, and the pngquant-bin package hid the error. `yum install gcc`.

**Comment by mmmpop** [comment]
> > it suddenly comes up last night.
> 
> > It's very boring
> 
> This is so npm typically. Everything is unstable like shit. You install random shit, you get random errors, you get random answers from the community, and nothing is working.
> 
> Using npm is so frustrating. I still wonder why even using npm at all.

@TheFox this never happens on my projects using Elixir; this is an npm problem, not some exception due to so much collaboration.

**Comment by aredridel** [comment]
This isn't an npm bug. The install script in this repo hides compilation errors by accident.

**Comment by 1415926535** [comment]
### If Win10, try:
Installing [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) per [these Windows node-gyp instructions](https://github.com/nodejs/node-gyp#option-2) got me passed this issue when trying to `npm install` a Maizzle/Jigsaw app.

Back in 2015, this post solved it pretty much the same way. Look at this comment at the bottom from @Madrus. 

### [stackoverflow: How to install libpng-dev on windows?](https://stackoverflow.com/questions/26522310/how-to-install-libpng-dev-on-windows)

> Just wanted to add that using C++ runtime libraries on Windows sometimes is the only way to install nodejs components. One such component is e.g. browser-sync. Of course, you need to have those libraries installed on your machine. Fortunately, installing the free Visual Studio 2013 Community Edition is enough. – Madrus Apr 23 '15 at 15:15

**Comment by konstantin-gusarov** [comment]
hi,
after some workaround found:
`/usr/bin/ld: cannot open output file /tmp/gcccheck: Permission denied
collect2: error: ld returned 1 exit status
  Compiler: error ... gcc failed to compile anything (make sure it's installed and supports C99)`

fix `sudo chmod 777 /tmp/gcccheck`

**Comment by lucianene** [comment]
> Had the same issue on Ubuntu 18.04, fixed with `sudo apt install libpng-dev`

life saver

**Comment by yamid** [comment]
If you're on Windows and tried everything of above, just **open a terminal as admin** and run the npm command, in my case it was `gatsby new project` and it completed successfully without the *pngquant pre-build test failed* error

**Comment by joshchiucn** [comment]
I had this problem today,but i figured it out. In my case,when enter pngquant-bin/vendor directory and run png quant.exe, the system warned me vcruntime140.dll(it should be in C:\Windows\System32) was missing,so,i asked my collegue to send his file to me,and it worked...

**Comment by elderph** [comment]
I had this problem on ubuntu. I had libpng installed at v16 and pngquant installed via node_modules required libpng at v12. Once I installed this version it worked. Hope this helps someone.

**Comment by maxalmonte14** [comment]
This was the definitive solution for me on Ubuntu 18.04

https://github.com/papandreou/node-pngquant/issues/14#issuecomment-406181693

**Comment by samoldenburg** [comment]
I am getting increasingly frustrated by this issue. No matter what I do, this is where I end up:
```
  ⚠ The `/home/redacted/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/redacted/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

We're on RHEL 7.6
- Tried with Node 6, 8, 10, 11 (latest minor versions)
- Tried these in various combinations with npm 3.10.10 and 6.5.0
- libpng-devel is installed
- make, gcc are installed
- I have tried locking imagemin-pngquant to 5.0.1, and pngquant-bin to 3.1.1

Is there anything I'm missing?

**Comment by frederikbosch** [comment]
I am also interested in the solution. Which packages should be added before pngquant-bin can be compiled?

**Comment by skeeith** [comment]
install the following

sudo apt install
libpng*
build-essential
gcc
make
autoconf
libtool
pkg-config
nasm

OR copy this

"sudo apt install libpng* build-essential gcc make autoconf libtool pkg-config nasm"

after installation of packages.

delete node_modules folder and package-lock.json file.
run npm install.

you're welcome.

**Comment by IPWright83** [comment]
I recently encountered this error when trying to install PhantomJS. In the end we tried:

`npm install --force pnquant-bin:5.0.1` which left the directories around. Poking inside there and trying to run `pngquant.exe --version` on windows threw an error due to `VCRUNTIME140.dll` being missing. 

In our case installing some of the VC++ redistributables using `choco install vcredist140 --version 14.0.24215.1` fixed us.

**Comment by dial3x** [comment]
I encountered this on Windows.

I resolved the issue through installing node 11 and on the install screen where it asks to whether to chocolatey+boxstarter etc. choose yes. This will install python 2.7 and VS build tools.

After a restart the issue went away. I'm unsure exactly which package resolved the issue but it's an easy solution if anyone still having issues with windows.

**Comment by GiselleSerate** [comment]
Also a Windows user; I also upgraded node and this worked for me. Node is now 8.10.0.

**Comment by kopax** [comment]
Our CIs are stuck. Can we please get some information? 

```
(node:389) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
  ⚠ Response code 503 (Backend unavailable, connection timeout)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/mnt/mesos/sandbox/builds/kopaxgroup-api/link/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 122362ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-19T20_02_49_736Z-debug.log
ps process exited with code 1
ERROR: Job failed: exit code 1
```

Any idea how we can solve this? All our CIs are down.

**Comment by MM263** [comment]
I have the same error as @kopax. Fails on installing gatsby-plugin-sharp

**Comment by JasonKaz** [comment]
The build/install process for pngquant-bin is referencing this URL: https://raw.github.com/imagemin/pngquant-bin/

Found in ~/node_modules/pngquant-bin/lib/index.js

Looks like raw.github.com is just down and is causing this issue.

**Comment by gabrielerzinger** [comment]
Any update on this?

**Comment by aarondfrancis** [comment]
My deploys are currently stuck on this. Are there any workarounds?

**Comment by david0603** [comment]
ditto

**Comment by aarondfrancis** [comment]
Where are yall hosted? It looks like it still works fine locally, but I can't get my builds to succeed on Digital Ocean. I'm using v`4.0.0` and just verified that the raw.github urls work fine in my browser:  https://github.com/imagemin/pngquant-bin/tree/v4.0.0/vendor.

Is any of this helpful? Gotta get building again...

**Comment by gabrielerzinger** [comment]
> Where are yall hosted? It looks like it still works fine locally, but I can't get my builds to succeed on Digital Ocean. I'm using pngquant-bin v`4.0.0` and just verified that the raw.github urls work fine in my browser: https://github.com/imagemin/pngquant-bin/tree/v4.0.0/vendor.
> 
> Is any of this helpful? Gotta get building again...

Maybe you have a successful cache/already installed locally? Also the URL that the module look up for is quite diff than the one you sent, its something like

> https://raw.github.com/imagemin/pngquant-bin/v3.1.1/vendor

**Comment by aarondfrancis** [comment]
> Also the URL that the module look up for is quite diff than the one you sent, its something like

If you click all the way through to one of the binaries and then hit "view raw", you get a much more similar URL
> https://github.com/imagemin/pngquant-bin/blob/v4.0.0/vendor/linux/x86/pngquant?raw=true

*BUT*, that _is_ different than the subdomained `raw.github.com` version the library is asking for. The browser version is `github.com` with a `?raw=true`.

🤔

**Comment by jareks** [comment]
Not sure why, but this seems to help me on AWS:
`sudo yum install libpng libpng-devel`
Perhaps it makes build process skip some fetching?

**Comment by aarondfrancis** [comment]
I think this may be it: https://github.com/imagemin/pngquant-bin/pull/99

**Comment by atma** [comment]
`raw.githubusercontent.com` domain should be used, there is a fix in #99

**Comment by gabrielerzinger** [comment]
> `raw.githubusercontent.com` domain should be used, there is a fix in #99

Great job, hope this gets merged asap..

**Comment by aarondfrancis** [comment]
Knowing that that's the issue... are there any clever (hacky) workarounds we can implement until it gets merged?

**Comment by gabrielerzinger** [comment]
> Knowing that that's the issue... are there any clever (hacky) workarounds we can implement until it gets merged?

Maybe one can fork this repo and serve it in npm..?

**Comment by atma** [comment]
@sindresorhus @1000ch Can you help with the #99 please? All of our builds are in stuck because of this.

**Comment by narration-sd** [comment]
probably have to wait until he wakes up - it's about midnight in Norway right now...

**Comment by narration-sd** [comment]
or actually it may come sooner -- appears he's actually in Thailand, where it's just coming dawn...

**Comment by aarondfrancis** [comment]
https://twitter.com/bradbaris/status/1097979286953160707

**Comment by grantsru** [comment]
God bless all ya'll helping to get this resolved.

**Comment by simianarmy** [comment]
He's actually awake but is committed to farming in RDR2 for a few hours

**Comment by grantsru** [comment]
> He's actually awake but is committed to farming in RDR2 for a few hours

At least he's committed to something, right?

**Comment by gabrielerzinger** [comment]
raw GitHub is back online, your builds should be fine (by now)

**Comment by ChaitanyaKaranam** [comment]
Was still facing this issue on windows. Installing Node 11 with python and visual studio build tools solved this problem.

**Comment by MSmashal** [comment]
I have the same problem beginning today，on windows ，node v10.13.0.

**Comment by Cosmin-Parvulescu** [comment]
I was running on an Ubuntu 18.04LTS machine and had this issue. 
What happened is that a package got updated and the dependency needed the following packages in order to build:
- gcc
- make
- libpng-dev

So, `apt-get install -y gcc make libpng-dev` might do the trick. It worked for me. Then again, I also cleaned my system cache, composer vendors and npm node_modules.

**Comment by boweiliu** [comment]
For anyone still struggling with this on Ubuntu 18.04, I solved this by `locate libpng12.so.0` and adding the correct directory to my LD_LIBRARY_PATH.

**Comment by mwleinad** [comment]
Fixed it In Centos by running 
yum install -y lib-png libpng-devel pngquant libpng12 libpng12-devel

**Comment by SanJin-hx** [comment]
windows system, install Microsoft Visual C++

**Comment by GitGump** [comment]
@SanJin-hx windows system +1, is there other solution instead of installing Microsoft Visual C++？

**Comment by EthanHemo** [comment]
Is there a change to set the link to raw.githubusercontent.com as a parameter? 
In my organization there is no open internet connection and we use on premise registry to access npm packages. 
if there could be a flag to change the download to different URL i could refer it to my registry.

I'm running on redhat 7.6, libpng-devel is installed.

**Comment by kubilaycagri** [comment]
> I had the same issue but it is resolved by first installing libpng-dev
> Need to follow the following steps:
> sudo apt-get install libpng-dev
> and then run
> npm install -g pngquant-bin
> 
> that fixed the issue for me.
> 
> @anthonyaam no need to go to old versions for pngquant-bin

Thanks, I fixed.

**Comment by shoaibjdev** [comment]
> I had the same issue but it is resolved by first installing libpng-dev
> Need to follow the following steps:
> sudo apt-get install libpng-dev
> and then run
> npm install -g pngquant-bin
> 
> that fixed the issue for me.
> 
> @anthonyaam no need to go to old versions for pngquant-bin

It worked! thanks

**Comment by asifalix** [comment]
sudo apt install libpng-dev 

This will fix this issue

**Comment by sherbastian** [comment]
`wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb   && sudo dpkg -i /tmp/libpng12.deb   && rm /tmp/libpng12.deb `

**Comment by ivanzhang** [comment]
> I was running on an **Ubuntu 18.04LTS** machine and had this issue.
> What happened is that a package got updated and the **pngquant** dependant - in my case **vue-boostrap** - needed the following packages in order to build:
> 
> * gcc;
> * make;
> * libpng-dev.
> 
> So, `apt-get install -y gcc make libpng-dev` might do the trick. It worked for me. Then again, I also cleaned my system cache, composer vendors and npm node_modules.

this reply did the trick for ubuntu 19

**Comment by dcabanales** [comment]
> I was running on an **Ubuntu 18.04LTS** machine and had this issue.
> What happened is that a package got updated and the **pngquant** dependant - in my case **vue-boostrap** - needed the following packages in order to build:
> 
> * gcc;
> * make;
> * libpng-dev.
> 
> So, `apt-get install -y gcc make libpng-dev` might do the trick. It worked for me. Then again, I also cleaned my system cache, composer vendors and npm node_modules.

Thank u!! this works perfect!!!!

**Comment by bradley-varol** [comment]
Ubuntu 19 here and the following worked for me:
- `sudo apt install libpng-dev`
- `rm -rf node_modules/`
- `yarn install`

**Comment by NIMDP2891** [comment]
> I don't understand npm and npm doesn't understand versioning. For anyone else struggling, my "fix" was to remove our '**image-webpack-loader**' package dependency (which ultimately removed transitive dependency to imagemin-pngquant and pngquant-bin).

yes...this works...thanks...was stuck on this for 2 days....

**Comment by alexandresebrao** [comment]
Did a fresh install on **Fedora 31**, got that problem here is the fix:

`dnf install @development-tools libpng libpng-devel`

**Comment by alfa-dev** [comment]
You have to install manually.

On linux:
```bash
apt-get install libpng-dev -y --no-install-recommends
```

source: https://github.com/imagemin/imagemin-pngquant/issues/46#issuecomment-379604951

**Comment by shahab-k** [comment]
Ubuntu 16.04
pngquant-bin@4.0.0
node.js version v9.9.0
npm version 5.6.0

make 4.1-6 installed

**Comment by galaxydirector** [comment]
I have my Solution wowww it has been fixed!!!!! Ubuntu 15.0
1. npm install, which fails
2. sudo rm -rf node_modules
3. npm update
4. npm audit fix (this is the key step,. I think it fixes the dependency issue)
5. yarn install/whatever you wanna run

Bingo!!!

**Comment by ryancwalsh** [comment]
For me, "pngquant-bin" was a dependency only because of laravel-mix. Updating to laravel-mix 5.0 fix it for me: https://github.com/JeffreyWay/laravel-mix/releases

**Comment by pingserv** [comment]
> 
> 
> For me, "pngquant-bin" was a dependency only because of laravel-mix. Updating to laravel-mix 5.0 fix it for me: https://github.com/JeffreyWay/laravel-mix/releases

Thanks!!

**Comment by alijmlzd** [comment]
I finally fixed this issue by just installing these packages:
`apt install bash gcc make libpng-dev`

**Comment by 120dev** [comment]
> @sroy19 I ran that in my server and got a message that no package libpng-dev is available. :/
> 
> Also, my system has libpng installed as well.
under fedora : `sudo dnf install libpng-devel `

**Comment by HydraOrc** [comment]
On Ubuntu you can try to fix it with `apt-get install -y libpango1.0-dev` command, worked for older node v6

**Comment by fyupanquia** [comment]
> You have to install manually.
> 
> On linux:
> 
> ```shell
> apt-get install libpng-dev -y --no-install-recommends
> ```
> 
> source: [imagemin/imagemin-pngquant#46 (comment)](https://github.com/imagemin/imagemin-pngquant/issues/46#issuecomment-379604951)

Works for me

**Comment by beatrizsmerino** [comment]
I have an ERROR in the npm package pngquant-bin@6.0.0 when I install and use it on Windows but on MAC this version is working.

```
--------------------
You must install additional module [npm install pngquant-bin --save]!
It does not work properly on some OS! If you will get an error try use other module.
--------------------
```

![image](https://user-images.githubusercontent.com/14045148/90564318-778ffd00-e1a5-11ea-9d24-c9786ae23974.png)

I fixed this error by installing a older version npm package **`pngquant-bin@3.1.1`**. Any other version between 6.0.0 - 3.1.1 is not working.


```
npm uninstall pngquant-bin
npm install --save dev pngquant-bin@3.1.1
```

**Comment by sambacha** [comment]
Ubuntu fixes after xenial: 

[https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/15108504](https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/15108504)

download and install `libpng12-0_1.2.54-1ubuntu1.1_amd64.deb`


for Ubuntu r 19.04, and after  the `/lib directory` is a symlink to` /usr/lib` (this was not the case with Ubuntu 18.04 and older), and this causes the libpng12-0 installation to fail, since this package tries to create a link from` /lib/x86_64-linux-gnu/libpng12.so.0 ` to ` /usr/lib` which is already a symlink. So the `DEB `had to be repacked to get it to work on newer Ubuntu versions.

[http://ppa.launchpad.net/linuxuprising/libpng12/ubuntu/pool/main/libp/libpng/](http://ppa.launchpad.net/linuxuprising/libpng12/ubuntu/pool/main/libp/libpng/)

**Comment by seetaram-yadav-by** [comment]
> I had the same issue but it is resolved by first installing libpng-dev
> Need to follow the following steps:
> sudo apt-get install libpng-dev
> and then run
> npm install -g pngquant-bin
> 
> that fixed the issue for me.
> 
> @anthonyaam no need to go to old versions for pngquant-bin

Thanks this worked

**Comment by llamerr** [comment]
Similar problem with bin file. It simply does not exist `ls node_modules/pngquant-bin/vendor ` only have `source` inside it, no binaries

**Comment by kabab** [comment]
The host node_modules folder is copied in the docker build context, you should ignore the folder using `.dockerignore` 
```
node_modules
```

**Comment by 1000ch** [comment]
Like https://github.com/imagemin/pngquant-bin/issues/78#issuecomment-519334229, please make sure to install prerequisites before installing this package.

**Comment by mydansun** [comment]
> Ubuntu fixes after xenial:
> 
> https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/15108504
> 
> download and install `libpng12-0_1.2.54-1ubuntu1.1_amd64.deb`
> 
> for Ubuntu r 19.04, and after the `/lib directory` is a symlink to` /usr/lib` (this was not the case with Ubuntu 18.04 and older), and this causes the libpng12-0 installation to fail, since this package tries to create a link from`/lib/x86_64-linux-gnu/libpng12.so.0` to ` /usr/lib` which is already a symlink. So the `DEB `had to be repacked to get it to work on newer Ubuntu versions.
> 
> http://ppa.launchpad.net/linuxuprising/libpng12/ubuntu/pool/main/libp/libpng/

For 2022, this method still works!

**Comment by jrhager84** [comment]
How does this work for aws lambda? It doesn't work on my local machine *or* the lambda instance.

**Comment by yuezk** [comment]
Per the above discussion, `gcc` and `make` are required. And this command worked for me. 

```
sudo apt-get install -y gcc make libpng-dev
```

**Comment by vipulrawat** [comment]
This issue seems to resurrect every 6 to 8 months. Currently, it is happening on aws codebuilds.

**Comment by u3u** [comment]
If someone encounters the `MaxRedirectsError: pngquant failed to build, make sure that libpng-dev is installed` error, they can manually modify the installation script file and change the installation URL to `https` to resolve it.

```sh
vim node_modules/.pnpm/pngquant-bin@4.0.0/node_modules/pngquant-bin/lib/install.js
```

<img width="793" alt="image" src="https://github.com/imagemin/pngquant-bin/assets/20062482/33011570-9915-42b4-ab7c-c7e3c2787090">

**Comment by Mantorn** [comment]
> I finally fixed this issue by just installing these packages: `apt install bash gcc make libpng-dev`

worked 2023.10

wsl ubuntu 22
node 12.22.12

**Comment by mverch67** [comment]
Hello from 2026!

The only thing that worked for me in Ubuntu 22.10 is:
`sudo apt-get install libimagequant-dev`
